#!/usr/bin/env bash
#configures a server so that its http response contsins a header on web-01
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
#create the redirect_me
sudo sed -i '/server_name _;/a \        location /redirect_me {\n               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n       }' /etc/nginx/sites-enabled/default
# Create the custom 404 page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /404.html;\n        location = /404.html {\n                internal;\n                root /var/www/html;\n        }' /etc/nginx/sites-enabled/default
HOSTNAME=$(hostname)
sudo sed -i "/http {/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf
sudo service nginx restart