#!/usr/bin/env bash
#install and configure HAproxy on my server
sudo apt-get update
sudo apt-get -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > haproxy.log <<EOF
frontend uthmanfrontend
        bind *:80
        default_backend mywebserver

backend mywebserver
        balance roundrobin
        server web-01 54.237.35.136:80 check
        server web-02 18.209.224.238:80 check
EOF
sudo service haproxy restart